name: Curl Webpage

on:
  workflow_dispatch:  # This allows you to trigger it manually from the GitHub Actions UI

jobs:
  curl-request:
    runs-on: ubuntu-latest

    steps:
      - name: Make curl request
        run: |
          echo "Fetching webpage..."
          curl -v http://dinhash.github.io/

