name: Actions Plan

on:
  push:
    paths:
      - 'run-test/**'     # Only run if files under terraform/ change
  workflow_dispatch:
jobs:
  curl-request:
    runs-on: ubuntu-latest

    steps:
      - name: Make curl request
        run: |
          echo "Fetching webpage..."
          curl -v https://dinhash.github.io/
